### ISSUE TITLE
Design Track

### ISSUE THREAD

**Issue by guygastineau** [exercism/scheme#105]
## This Issue Tracks the Re-Design of the Core Exercises

- [x] Decide on Core Exercises
- [x] Determine Order of Core Exercises
- [x] Link each Side Exercises to a Core Exercise Prerequisite

**Comment by guygastineau** [comment]
## Exercises Table

| slug | core | unlocked by | difficulty | wip? |
| ----- | ------ | --------------- | ---------- | ------ |
| hello-world | yes | none | 1 | no |
| leap | yes | none | 2 | no |
| rna-transcription | yes | none | 2 | no |
| hamming | yes | none | 3 | no |
| grains | yes | none | 3 | no |
| anagram | yes | none | 4 | no |
| difference-of-squares | yes | none | 3 | no |
| pascals-triangle | yes | none | 5 | no |
| bob | no | none | 1 | no |
| raindrops | no | none | 1 | no |
| robot-name | no | none | 1 | no |
| phone-number | no | none | 1 | no |
| nucleotide-count | no | none | 1 | no |
| list-ops | no | none | 1 | no |
| scrabble-score | no | none | 1 | no |
| word-count | no | none | 1 | no |
| two-fer | no | none | 1 | no |
| sieve | no | none | 2 | yes |
| change | no | none | 5 | yes |
| sublist | no | none | 2 | yes |
| atbash-cipher | no | none | 1 | yes |
| knapsack | no | none | 6 | yes |

**Comment by guygastineau** [comment]
The table above is just to provide a really easy visual that we can edit for rethinking the track design.

**Comment by jitwit** [comment]
This is based on config as it is now?

**Comment by guygastineau** [comment]
Yes, that is based on the current status of `config.ss`.

I have seen deprecation in the problem specifications.  It is probably possible to deprecate exercises on the track level.

I don't see any reason to remove bob from the track entirely.  It gets a lot of hate, but there are some decent lessons to be learned.  Is removing it from core enough vindication for you ? :rofl:

**Comment by jitwit** [comment]
Yeah sure. I don't personally feel like porting that exercise to the new format, if you'd like to take care of it haha

**Comment by guygastineau** [comment]
Yeah, I've got it covered.

We could use4 this issue as a place to post which exercises still need to be ported to the new system.

**Comment by guygastineau** [comment]
## Ported List
- [ ] Hello World
- [ ] Leap
- [ ] RNA Transcription
- [ ] Hamming
- [ ] Grains
- [ ] Anagram
- [ ] Difference of Squares
- [ ] Pascal's Triangle
- [ ] Bob
- [ ] Raindrops
- [ ] Robot Name
- [ ] Phone Number
- [ ] Nucleotide Count
- [ ] List Ops
- [ ] Scrabble Score
- [ ] Word Count
- [ ] Two Fer
- [ ] Sieve
- [ ] Change
- [ ] Sub-List
- [ ] Atbash Cipher
- [ ] Knapsack

**Comment by jitwit** [comment]
To get more challenging problems in core we could consider knapsack?

**Comment by guygastineau** [comment]
Sure.

I also think that robot-name is a good candidate to be in core.  I think that message passing is so natural for it that it is a good core exercise to fortify that concept.

**Comment by guygastineau** [comment]
As is there are only 7 real exercises in core.

Adding those two would give us 9.

Ideally we will be able to get 30 - 40 exercises total in the track by the end of October.

At that point it would be nice to have at least twelve core exercises.  For now I think 9 would be a great number to have in the core

**Comment by jitwit** [comment]
> Sure.
> 
> I also think that robot-name is a good candidate to be in core. I think that message passing is so natural for it that it is a good core exercise to fortify that concept.

My only issue with it is that it's not an easy problem to mentor. If I'm the only person reviewing solutions (which I am at the moment), I don't want to dread certain problems

**Comment by guygastineau** [comment]
Sure, I feel confident in mentoring these core exercises now, so I am willing to mentor here too. To be honest I am tired of Rust, and I hardly mentor bash anymore (mostly just maintenance).

**Comment by guygastineau** [comment]
I like the robot-name exercise, so I am willing to take all of them.

**Comment by jitwit** [comment]
There are no canonical tests for robot name. I'm all for it being in core, but developing an implementation with good tests and solutions might take some work. Perhaps we could prioritize adding it, but not have it block using the new format?

**Comment by guygastineau** [comment]
Sure, there is no reason for it to block.

**Comment by jitwit** [comment]
Getting close eh? I'll think about the core track and requirements. What else needs to be done?

We can mark deprecated the exercises that aren't ported and re-include them as we get solutions together, though we have a fair few problems now!

**Comment by jitwit** [comment]
I'm a fan of deprecating list ops for now since the canonical data file has infix notation specification that makes our way of parsing tests annoying

**Comment by guygastineau** [comment]
I am going to go through the docs again tonight to verify that everything the students need to know is at least up to date and not too confusing.

I also think we need #111 merged, so that regenerating the `config.json` is more automatic.

**Comment by guygastineau** [comment]
This is good progress here.

I guess we should leave this open until I am finished porting `bob` and `robot-name` at least.

**Comment by jitwit** [comment]
Yeah. It can also be a reasonable place to debate problem topics, difficulties, unticked-bys, etc.

**Comment by jitwit** [comment]
on to v3 i suppose...
