### ISSUE TITLE
Launching the new version

### ISSUE THREAD

**Issue by guygastineau** [exercism/scheme#121]
As far as I can tell right now the only thing that is stopping us from launching the new version is the lack of information about how to run the tests in the `README.md` files of the tests.

I think with such a change it should be included.

I think there is a way to include it in the golang template for it by reference, but if that doesn't work it can be inlined in the template.

The bash track has a good example of inlining this info in the template
[bash readme template](https://github.com/exercism/bash/blob/master/config/exercise_readme.go.tmpl)

**Comment by guygastineau** [comment]
@jitwit  my 2 cents on the progress toward launch

**Comment by jitwit** [comment]
Sounds reasonable, hopefully using the template is straightforward

**Comment by guygastineau** [comment]
So I got #122 up to handle this.

We should still look through everything again.

@jitwit if you want to look through, and see if you have any questions about possible compatibility concerns that might be useful too.  You might catch something I didn't notice just by wondering.

**Comment by jitwit** [comment]
Something else to consider: some of the default readmes have descriptions which don't jive with the scheme tests/solutions. Perhaps we could add comments to the exercises in such cases to explain the approach to take? Unless there's a better way with the go template?

**Comment by guygastineau** [comment]
There is a file we can add to a `.meta` directory (inside an exercise's directory) that will get included.

I need to track down the name again.

**Comment by guygastineau** [comment]
We can out a file `hints.md` into the `.meta` subdirectory of a file, and it should get included.

So, adding a readme extenaion to `bob` would require this file be present:
`scheme/exercises/bob/.meta/hints.md`

**Comment by guygastineau** [comment]
I wont have a problem if you add all of these at once.

**Comment by jitwit** [comment]
Sounds good. These should potentially be specified in the `code/exercises/problem/*` directories, I'll try it out

**Comment by guygastineau** [comment]
Launched
