### ISSUE TITLE
Run Exercise Tests in Travis

### ISSUE THREAD

**Issue by guygastineau** [exercism/scheme#133]
This issue is for tracking #87 

#### Provide access to the `srfi` collection for chez
- This might require using a git submodule
- It would require setting the `CHEZSCHEMELIBDIRS` environment variable in `Travis`
- @jitwit please let us know if the srfi collection is needed
- Also, if that is more than we want to do to this project, should we consider only running the tests in `Guile` for the `Travis` checks?

**Comment by jitwit** [comment]
The srfi's are a dependency of the json libraries. The example solutions (and the test suite) are designed to not rely on anything but the base `(rnrs (6))` library. One thing we could do is add a rule to the `Makefile` to only run the tests against the example solutions. `code/stub-makefile` has the basic anatomy for that

**Comment by jitwit** [comment]
I think we should still try to run tests using both `Guile` and `Chez`

**Comment by guygastineau** [comment]
Okay, thanks for the clarification @jitwit.

I though this was the case, but I wanted to have these concerns documented to make sure they were answered.

**Comment by guygastineau** [comment]
Yay :confetti_ball:
