### ISSUE TITLE
Phone Number side exercise instructions do not match test.

### ISSUE THREAD

**Issue by David-Herriot** [exercism/scheme#178]
I have just noticed the instructions for the side exercise "Phone Number" do not state that the output has to conform to the specifications for NANP numbers. Yet the test checks for exchange codes and area codes.

From the page: Your task is to clean up differently formatted telephone numbers **by removing punctuation and the country code** (1) if present.

I think it should be specified on the instruction page that `clean` should result  in an error if the number does not conform to the specification and list examples of inputs that should result in an error.

**Comment by jitwit** [comment]
This is a good catch, thanks!

**Comment by guygastineau** [comment]
@David-Herriot this is probably an issue with the upstream instructions/documentation in the exercism/problem-specifications repository.  If you haven't already, I suggest you get it changed there to benefit the tracks for all languages.
