### ISSUE TITLE
Missing Makefiles

### ISSUE THREAD

**Issue by danilopiazza** [exercism/scheme#247]
It looks like the following exercises do not have a Makefile:

- Accumulate
- Acronym
- Armstrong Numbers
- Octal
- Roman Numerals
- Sum Of Multiples
- Triangle
- Trinary

I think the standard Makefile (copied from `input/skeleton-makefile`) should be added to the above exercises.

**Comment by guygastineau** [comment]
Ficed as of #253 including the work from #247 for which @danilopiazza received credit as the author.  Thanks again.
