### ISSUE TITLE
Errors in the auto testing system, submission always fails

### ISSUE THREAD

**Issue by SohamG** [exercism/scheme#259]
Hello,

I just did the hello world scheme exercise. I can get it to pass on my local machine with the exercism CLI with Guile but I the website refuses to accept it with a "an error occurred" message.

![image](https://user-images.githubusercontent.com/7116239/170253497-9c04e260-d6c0-45cb-a4dc-f34606237ab2.png)

![image](https://user-images.githubusercontent.com/7116239/170253583-012d37fa-342e-4071-8090-0c4cddc85385.png)

Let me know if any further info is needed

**Comment by yzk23** [comment]
Same thing with me

**Comment by AkibAzmain** [comment]
The `test.scm` also doesn't work.  Changing `hello-world.scm` to `./hello-world.scm` works.

**Comment by guygastineau** [comment]
@AkibAzmain you need to use make to choose the scheme implementation for the tests.

@SohamG @yzk23 I have a pull request, exercism/scheme-test-runner#32, awaiting final approval.  It adds true version 2 test runner interface compliance.  The new test system, #262, required for this is also ready for production once the test-runner is updated.  

There is a legacy compatibility fallback in the new test-runner.  So, old tests should run "just as they do now" except failure while loading the student code will be caught.  You will need to update your exercises after #262 is merged to take advantage of the improved reporting on the website.

**Comment by AkibAzmain** [comment]
@SohanG Does `make guile` work for you locally?

**Comment by AkibAzmain** [comment]
@guygastineau,

> @AkibAzmain you need to use make to choose the scheme implementation for the tests.

I'm running `make guile`.  It's failing with this:

```
guile test.scm 
Backtrace:
           0 (primitive-load-path "scheme/hello-world/hello-world.scm")

ERROR: In procedure primitive-load-path:
In procedure primitive-load-path: Unable to find file "scheme/hello-world/hello-world.scm" in load path
make: *** [Makefile:15: guile] Error 1
```

**Comment by guygastineau** [comment]
@AkibAzmain hmm, it shouldn't be using `primitive-load-path`.  It sounds toe like your test version is very old.  You could try updating the exercise.

**Comment by SohamG** [comment]
> @SohamG Does `make guile` work for you locally?

Sorry for the delayed response but yes, make guile would work locally which is how I did the first like 4 exercises

**Comment by guygastineau** [comment]
@SohamG I responded to your issue is the test runner repository.  As stated there, the new test-runner is now pushed to main.  I don't if there is a lag for the exercism,io webapp to use the new test runner, but hopefully it works now.  I expect the fix @austinmlv introduced is what will fix your issue in the test runner, so things should work for you know.  Out of interest, do you have `chez scheme` installed?  what happens when you run `chez --script test.scm --docker` in your exercise directory?

**Comment by guygastineau** [comment]
We finally got #262 merged!  Please upgrade your exercises and try to submit solutions.  I have empirical and theoretical evidence that this issue is resolved, but I will give you all a few days to respond before closing it.

**Comment by AkibAzmain** [comment]
> Sorry, for some reason there is a bug in the test-runner as used by the website, but it is not caught by the tests. I am investigating it now via [exercism/scheme-test-runner#33](https://github.com/exercism/scheme-test-runner/issues/33) . Sorry for the trouble, I hoipe we can get this resolved as quickly as possible.

The website says syntax error, right?  Here is it: https://exercism.org/tracks/scheme/exercises/hamming/solutions/AkibAzmain.  It passes on my machine.

**Comment by yzk23** [comment]
It works for me!

**Comment by guygastineau** [comment]
@AkibAzmain the issue with the production test runner should be resolved.  

Everyone here, a new fix has been pushed, and results look good.  Please take your concerns to exercism/scheme-test-runner#31 if any issues persist for you.
