### ISSUE TITLE
Add additional exercises

### ISSUE THREAD

**Issue by BNAndras** [exercism/scheme#291]
Here are some exercises I'd like to port in the near future, having done so on other tracks.

- [ ] all-your-base
- [ ] bank-account
- [ ] etl
- [ ] high-scores
- [ ] isogram
- [ ] list-ops
- [ ] pop-count

**Comment by guygastineau** [comment]
Thank you for spending some time working on this track.  I'm gonna check out your PR, and I'll try to get a solid review for you in the next few days.

**Comment by BNAndras** [comment]
Sorry about the delay. I was helping port exercises for CFML, Lua, and Vim script since they're featured next month for #12in23. I'll start working on this next week. I added all-your-base and list-ops to the tracking list so we can replace the deprecated exercises mentioned in #294
