### ISSUE TITLE
ubuntu missing required srfi and srfi-64 modules

### ISSUE THREAD

**Issue by PurityControl** [exercism/scheme#30]
This is not technically a problem with the exercism instructions, but ubuntu's guile packages (both 1.8 and 2.0) do not come with the required srfi and srfi-64 modules.
As a result the test file cannot run and throws an error.

Given the popularity of ubuntu for linux usage it may be worth mentioning this in the help file to save a lot of heartache for people wanting to get started with scheme.

I have compiled the latest guile from sources on ubuntu and that works fine. I would be happy to supply some instructions or a script for doing this if it would help at all. 

This is for ubuntu 14.04 lts and I haven't tried this on a newer ubuntu version.

**Comment by kytrinyx** [comment]
This would be very helpful. We're in the middle of transitioning the docs from https://github.com/exercism/docs to https://github.com/exercism/xscheme/tree/master/docs

At the moment the first is what is actually shown to users. If you put it one place I'll make sure it goes into the other place.

**Comment by canweriotnow** [comment]
Wow, thanks for catching this @PurityControl - I'll have to double check the version I'm running at home as I haven't seen this. Not bundling the srfi's with the guile distribution is really aberrant behavior, it's not like they're considered "extra" and to be relegated to guile-lib. I'll follow up checking 14.10, 15.04 and if necessary open an issue on Launchpad.
