### ISSUE TITLE
Readme and Test Suite not available from Point Mutations

### ISSUE THREAD

**Issue by PurityControl** [exercism/scheme#44]
I'm not sure whether this issue is specific to scheme but now the point mutations exercise has been renamed to hamming, when you look at an older problem named as "Point Mutations" if you click on the "Readme" or "Test Suite" links you get an error "No implementation of 'point-mutations' in track 'scheme'"
![screen shot 2016-07-02 at 22 11 24](https://cloud.githubusercontent.com/assets/7509180/16542478/ffb5e72a-40a1-11e6-854a-ba486181f202.png)

Is this an issue for exercism.io  rather than here?

**Comment by yurrriq** [comment]
Seems like a website issue to me. I think there's a discussion on an issue in x-common maybe about cleaning up he deprecation and renaming of exercises.

**Comment by kytrinyx** [comment]
Yepp, this is a website bug.
